version: '2'

services:
  minio:
    image: minio/minio
    restart: always
    volumes:
      - ./minio:/export
    ports:
      - "9090:9000"
    env_file:
      - minio.env
    command: server /export

  gogs:
    image: gogs/gogs
    volumes:
      - ./gogs:/data
    ports:
      - "10022:22"
      - "3000:3000"
    restart: always

  drone-server:
    image: drone/drone
    privileged: true
    ports:
      - "8000:80"
    volumes:
      - ./drone:/var/lib/drone/
      - /var/run/docker.sock:/var/run/docker.sock
    restart: always
    environment:
      - DRONE_ADMIN=<admin>
      - DRONE_OPEN=true
      - DRONE_SERVER_HOST=zendikar.fr:8000
      - DRONE_SERVER_PROTO=http
      - DRONE_RPC_SECRET=<drone-secret>
      - DRONE_GOGS_SERVER=http://gogs:3000
      - DRONE_GOGS_SKIP_VERIFY=false
    links:
      - gogs
  drone-agent:
    image: drone/drone-runner-docker
    restart: always
    depends_on:
      - drone-server
    links:
      - drone-server
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - DRONE_RPC_HOST=drone-server
      - DRONE_RPC_PROTO=http
      - DRONE_RPC_SECRET=<drone-secret>
  registry:
    image: registry
    ports:
#      - "127.0.0.1:5000:5000"
      - "5000:5000"
    volumes:
      - /registry/lib:/var/lib/registry
    restart: always
